### ISSUE TITLE
Argument 1 passed to MatthiasMullie\Minify\CSS::move() must be an instance of MatthiasMullie\PathConverter\ConverterInterface

### ISSUE THREAD

**Issue by alsopeter** [suncho26/opencart-js-css-minifier#1]
Hello,

It looks like your code is for OpenCart 3 series. I changed it for OpenCart 2.0.3.1. I ended up with error:
Argument 1 passed to MatthiasMullie\Minify\CSS::move() must be an instance of MatthiasMullie\PathConverter\ConverterInterface, instance of MatthiasMullie\PathConverter\Converter given, called in system/library/minify/CSS.php on line 322 and defined in system/library/minify/CSS.php:344

Debugging brought me deeper in the minifier then I expected to be necessary. That is why I downloaded minify and path-converter from matthiasmullie on Git and installed it without composer using:

$path =  DIR_SYSTEM . 'library';
require_once $path . '/minify/src/Minify.php';
require_once $path . '/minify/src/CSS.php';
require_once $path . '/minify/src/JS.php';
require_once $path . '/minify/src/Exception.php';
require_once $path . '/minify/src/Exceptions/BasicException.php';
require_once $path . '/minify/src/Exceptions/FileImportException.php';
require_once $path . '/minify/src/Exceptions/IOException.php';
require_once $path . '/path-converter/src/ConverterInterface.php';
require_once $path . '/path-converter/src/Converter.php';
use MatthiasMullie\Minify;

The error was gone.
I did't had the time to find out if it has something to do with OpenCart 2.0.3.1, but now it runs like a charm. I removed all js en css files calls in header.tpl, and added them in header.php using addStyle and addScript from the document library. Don't need a tool to conclude that this makes openCart running much faster.

**Comment by georgikolev7** [comment]
Hello @alsopeter, actually the code is written for version 2.0.3.1, not for OpenCart 3.0, that's why I not guarantee it will work on 3.0.

The minify library used in this project is the latest version, I don't know why there is a difference when you download it again.

The "move()" function in the library is very interesting.

For example: if you have 14 CSS files and 3 of them have **@media (max-width: 400px)** media query inside, function catch all code inside this media query in all files, create the same media query in the merged file and put all code from all files for this query inside.

So the error is probably generated from some mistake in your CSS code. It's better to ask the author of the library here - https://github.com/matthiasmullie/minify.

**Comment by mupcku** [comment]
Исках и аз да го тествам, използвам opencart 2.1.0.1 но и аз имам същата грешка
Fatal error: Uncaught TypeError: Argument 1 passed to MatthiasMullie\Minify\CSS::move() must be an instance of MatthiasMullie\PathConverter\ConverterInterface, instance of MatthiasMullie\PathConverter\Converter given, called in /home/mupckuco/dev/system/library/minify/CSS.php on line 322 and defined in /home/mupckuco/dev/system/library/minify/CSS.php:344 Stack trace: #0 /home/mupckuco/dev/system/library/minify/CSS.php(322): MatthiasMullie\Minify\CSS->move(Object(MatthiasMullie\PathConverter\Converter), 'DIR_HOMEcatalog...') #1 /home/mupckuco/dev/system/library/minify/Minify.php(102): MatthiasMullie\Minify\CSS->execute('/home/mupckuco/...') #2 /home/mupckuco/dev/vqmod/vqcache/vq2-system_library_compress.php(37): MatthiasMullie\Minify\Minify->minify('/home/mupckuco/...') #3 /home/mupckuco/dev/vqmod/vqcache/vq2-system_library_document.php(76): Compress->merge_css(Array) #4 /home/mupckuco/dev/system/storage/modification/catalog/controller/common/header.php(33): Document->getStyles() #5 /home/mupckuco/dev/vqmod/vqcache/vq2-sys in /home/mupckuco/dev/system/library/minify/CSS.php on line 344
